spring:
  application:
    name: "cloud-config"
  profiles:
    include:
      - "native"  # 使用本地文件当做文件存储目录必须激活此profile
  cloud:
    config:
      server:
        native:
          search-locations:
            - "classpath:/config"
            - "classpath:/config/{application}"

server:
  port: 3344

eureka:
  instance:
    # 显示在eureka-dashboard上的名称
    instance-id: "cloud-config-3344"
    # 在eureka-dashboard上显示IP
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
        readiness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
            - "readinessStateProbeIndicator"
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
  info:
    git:
      enabled: true
      mode: simple
    env:
      enabled: false
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"

info: { }
