spring:
  application:
    name: "cloud-service-provider"

server:
  port: 8001

eureka:
  instance:
    # 显示在eureka-dashboard上的名称
    instance-id: "cloud-service-provider-8001"
    # 在eureka-dashboard上显示IP
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
        readiness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
            - "readinessStateProbeIndicator"
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
  info:
    git:
      enabled: true
      mode: simple
    env:
      enabled: false
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"

info: { }
